version: "3.2"
services:
  backend:
    build: 
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    entrypoint:
      - /django-entrypoint.sh
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - backend